export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard_view",

  PRODUIT_VIEW: "produit_view",
  PRODUIT_CREATE: "produit_create",
  PRODUIT_UPDATE: "produit_update",
  PRODUIT_REACTIVER: "produit_reactiver",

  VENTE_VIEW: "vente_view",
  VENTE_CREATE: "vente_create",
  VENTE_CANCEL: "vente_cancel",

  CAISSE_VIEW: "caisse_view",

  DETTE_VIEW: "dette_view",
  DETTE_CREATE: "dette_create",
  DETTE_UPDATE: "dette_update",

  PAIEMENT_VIEW: "paiement_view",
  PAIEMENT_CREATE: "paiement_create",

  COMMANDE_VIEW: "commande_view",
  COMMANDE_CREATE: "commande_create",
  COMMANDE_UPDATE: "commande_update",
  COMMANDE_ANNULER: "commande_annuler",

  DEPENSE_VIEW: "depense_view",
  DEPENSE_CREATE: "depense_create",

  RAPPORT_VIEW: "rapport_view",

  CLIENT_VIEW: "client_view",

  APPROVISIONNEMENT_VIEW: "approvisionnement_view",
  APPROVISIONNEMENT_CREATE: "approvisionnement_create",

  MESSAGING_VIEW: "messaging_view",
  MESSAGING_SEND: "messaging_send",

  USER_MANAGE: "user_manage",
};

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: ["*"],

  ADMIN: ["*"],

  CAISSIER: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.VENTE_VIEW,
    PERMISSIONS.VENTE_CREATE,

    PERMISSIONS.CAISSE_VIEW,

    PERMISSIONS.COMMANDE_VIEW,
    PERMISSIONS.COMMANDE_CREATE,
    PERMISSIONS.COMMANDE_UPDATE,
    PERMISSIONS.COMMANDE_ANNULER,

    PERMISSIONS.PAIEMENT_VIEW,
    PERMISSIONS.PAIEMENT_CREATE,

    PERMISSIONS.DETTE_VIEW,
    PERMISSIONS.DETTE_CREATE,
    PERMISSIONS.DETTE_UPDATE,

    PERMISSIONS.PRODUIT_VIEW,

    PERMISSIONS.DEPENSE_VIEW,
    PERMISSIONS.DEPENSE_CREATE,

    PERMISSIONS.CLIENT_VIEW,

    PERMISSIONS.APPROVISIONNEMENT_VIEW,

    PERMISSIONS.MESSAGING_VIEW,
    PERMISSIONS.MESSAGING_SEND,

    PERMISSIONS.RAPPORT_VIEW,

  ],

  COMPTABLE: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.RAPPORT_VIEW,

    PERMISSIONS.PAIEMENT_VIEW,

    PERMISSIONS.DETTE_VIEW,
    PERMISSIONS.DETTE_UPDATE,

    PERMISSIONS.DEPENSE_VIEW,
    PERMISSIONS.DEPENSE_CREATE,

    PERMISSIONS.MESSAGING_VIEW,
    PERMISSIONS.MESSAGING_SEND,
  ],
};